table DimDepartment
	lineageTag: a1000002-0000-0000-0000-000000000001

	column DepartmentKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a1000002-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: DepartmentKey

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: a1000002-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column DivisionGroup
		dataType: string
		lineageTag: a1000002-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: DivisionGroup

		annotation SummarizationSetBy = Automatic

	column CommandingOfficer
		dataType: string
		lineageTag: a1000002-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: CommandingOfficer

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: string
		lineageTag: a1000002-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column HeadcountWeight
		dataType: int64
		formatString: 0
		lineageTag: a1000002-0000-0000-0000-000000000008
		summarizeBy: none
		sourceColumn: HeadcountWeight

		annotation SummarizationSetBy = Automatic

	/// Per-department weight used to apportion the Imperial Treasury subsidy.
	/// A department's allocated share = CostDriverWeight / SUM(CostDriverWeight).
	/// Zero for the Station-Wide (Unallocated) dept which carries no budget.
	column CostDriverWeight
		dataType: int64
		formatString: 0
		lineageTag: a1000002-0000-0000-0000-000000000009
		summarizeBy: sum
		sourceColumn: CostDriverWeight

		annotation SummarizationSetBy = Automatic

	partition DimDepartment = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Csv.Document(File.Contents("b:\VS Code Files\PBI Project\Star Wars\data\DimDepartment.csv"), [Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangeTypes = Table.TransformColumnTypes(PromoteHeaders, {
				        {"DepartmentKey", Int64.Type},
				        {"Department", type text},
				        {"DivisionGroup", type text},
				        {"CommandingOfficer", type text},
				        {"Sector", type text},
				        {"HeadcountWeight", Int64.Type},
				        {"CostDriverWeight", Int64.Type}
				    })
				in
				    ChangeTypes

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

