table DimEngagementType
	lineageTag: a2000003-0000-0000-0000-000000000001

	column EngagementTypeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a2000003-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: EngagementTypeKey

		annotation SummarizationSetBy = Automatic

	column EngagementType
		dataType: string
		lineageTag: a2000003-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: EngagementType

		annotation SummarizationSetBy = Automatic

	column Domain
		dataType: string
		lineageTag: a2000003-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Domain

		annotation SummarizationSetBy = Automatic

	column IntensityWeight
		dataType: int64
		formatString: 0
		lineageTag: a2000003-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: IntensityWeight

		annotation SummarizationSetBy = Automatic

	column IsSuperlaser
		dataType: string
		lineageTag: a2000003-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: IsSuperlaser

		annotation SummarizationSetBy = Automatic

	partition DimEngagementType = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Csv.Document(File.Contents("b:\VS Code Files\PBI Projects\Star Wars\data\DimEngagementType.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangeTypes = Table.TransformColumnTypes(PromoteHeaders, {
				        {"EngagementTypeKey", Int64.Type},
				        {"EngagementType", type text},
				        {"Domain", type text},
				        {"IntensityWeight", Int64.Type},
				        {"IsSuperlaser", type text}
				    })
				in
				    ChangeTypes

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

