table DimEnemyFaction
	lineageTag: a2000001-0000-0000-0000-000000000001

	column FactionKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a2000001-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: FactionKey

		annotation SummarizationSetBy = Automatic

	column Faction
		dataType: string
		lineageTag: a2000001-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Faction

		annotation SummarizationSetBy = Automatic

	column FactionType
		dataType: string
		lineageTag: a2000001-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: FactionType

		annotation SummarizationSetBy = Automatic

	column ThreatLevel
		dataType: string
		lineageTag: a2000001-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: ThreatLevel

		annotation SummarizationSetBy = Automatic

	column HomeRegion
		dataType: string
		lineageTag: a2000001-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: HomeRegion

		annotation SummarizationSetBy = Automatic

	partition DimEnemyFaction = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Csv.Document(File.Contents("b:\VS Code Files\PBI Projects\Star Wars\data\DimEnemyFaction.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangeTypes = Table.TransformColumnTypes(PromoteHeaders, {
				        {"FactionKey", Int64.Type},
				        {"Faction", type text},
				        {"FactionType", type text},
				        {"ThreatLevel", type text},
				        {"HomeRegion", type text}
				    })
				in
				    ChangeTypes

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

