table DimLocation
	lineageTag: a1000005-0000-0000-0000-000000000001

	column LocationKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a1000005-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: LocationKey

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: a1000005-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Zone
		dataType: string
		lineageTag: a1000005-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Zone

		annotation SummarizationSetBy = Automatic

	column DeckLevel
		dataType: string
		lineageTag: a1000005-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: DeckLevel

		annotation SummarizationSetBy = Automatic

	column LocationType
		dataType: string
		lineageTag: a1000005-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: LocationType

		annotation SummarizationSetBy = Automatic

	partition DimLocation = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Csv.Document(File.Contents("b:\VS Code Files\PBI Projects\Star Wars\data\DimLocation.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangeTypes = Table.TransformColumnTypes(PromoteHeaders, {
				        {"LocationKey", Int64.Type},
				        {"Location", type text},
				        {"Zone", type text},
				        {"DeckLevel", type text},
				        {"LocationType", type text}
				    })
				in
				    ChangeTypes

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

