table FactHeadcount
	lineageTag: b1000003-0000-0000-0000-000000000001

	column MonthDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b1000003-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: MonthDateKey

		annotation SummarizationSetBy = Automatic

	column DepartmentKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b1000003-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: DepartmentKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RoleKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b1000003-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: RoleKey

		annotation SummarizationSetBy = Automatic

	column Headcount
		dataType: int64
		formatString: #,0
		lineageTag: b1000003-0000-0000-0000-000000000005
		summarizeBy: sum
		sourceColumn: Headcount

		annotation SummarizationSetBy = Automatic

	column Hires
		dataType: int64
		formatString: #,0
		lineageTag: b1000003-0000-0000-0000-000000000006
		summarizeBy: sum
		sourceColumn: Hires

		annotation SummarizationSetBy = Automatic

	column Separations
		dataType: int64
		formatString: #,0
		lineageTag: b1000003-0000-0000-0000-000000000007
		summarizeBy: sum
		sourceColumn: Separations

		annotation SummarizationSetBy = Automatic

	column CombatLosses
		dataType: int64
		formatString: #,0
		lineageTag: b1000003-0000-0000-0000-000000000008
		summarizeBy: sum
		sourceColumn: CombatLosses

		annotation SummarizationSetBy = Automatic

	column AverageMonthlyPayCredits
		dataType: int64
		formatString: #,0
		lineageTag: b1000003-0000-0000-0000-000000000009
		summarizeBy: none
		sourceColumn: AverageMonthlyPayCredits

		annotation SummarizationSetBy = Automatic

	column PayrollCostCredits
		dataType: int64
		formatString: #,0
		lineageTag: b1000003-0000-0000-0000-00000000000a
		summarizeBy: sum
		sourceColumn: PayrollCostCredits

		annotation SummarizationSetBy = Automatic

	partition FactHeadcount = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Csv.Document(File.Contents("b:\VS Code Files\PBI Projects\Star Wars\data\FactHeadcount.csv"), [Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangeTypes = Table.TransformColumnTypes(PromoteHeaders, {
				        {"MonthDateKey", Int64.Type},
				        {"DepartmentKey", Int64.Type},
				        {"RoleKey", Int64.Type},
				        {"Headcount", Int64.Type},
				        {"Hires", Int64.Type},
				        {"Separations", Int64.Type},
				        {"CombatLosses", Int64.Type},
				        {"AverageMonthlyPayCredits", Int64.Type},
				        {"PayrollCostCredits", Int64.Type}
				    }),
				    #"Replaced Value" = Table.ReplaceValue(ChangeTypes,0,null,Replacer.ReplaceValue,{"Hires"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",0,null,Replacer.ReplaceValue,{"CombatLosses"})
				in
				    #"Replaced Value1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

