table FactReadiness
	lineageTag: b2000003-0000-0000-0000-000000000001

	column SnapshotDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b2000003-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: SnapshotDateKey

		annotation SummarizationSetBy = Automatic

	column ConditionKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b2000003-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: ConditionKey

		annotation SummarizationSetBy = Automatic

	column ThreatIndex
		dataType: double
		formatString: 0.0
		lineageTag: b2000003-0000-0000-0000-000000000004
		summarizeBy: average
		sourceColumn: ThreatIndex

		annotation SummarizationSetBy = Automatic

	column TIESquadronsOperational
		dataType: int64
		formatString: #,0
		lineageTag: b2000003-0000-0000-0000-000000000005
		summarizeBy: average
		sourceColumn: TIESquadronsOperational

		annotation SummarizationSetBy = Automatic

	column TIESquadronsTotal
		dataType: int64
		formatString: #,0
		lineageTag: b2000003-0000-0000-0000-000000000006
		summarizeBy: average
		sourceColumn: TIESquadronsTotal

		annotation SummarizationSetBy = Automatic

	column SuperlaserChargePct
		dataType: double
		formatString: 0.0
		lineageTag: b2000003-0000-0000-0000-000000000007
		summarizeBy: average
		sourceColumn: SuperlaserChargePct

		annotation SummarizationSetBy = Automatic

	column ShieldIntegrityPct
		dataType: double
		formatString: 0.0
		lineageTag: b2000003-0000-0000-0000-000000000008
		summarizeBy: average
		sourceColumn: ShieldIntegrityPct

		annotation SummarizationSetBy = Automatic

	column TurbolaserBatteriesOnline
		dataType: int64
		formatString: #,0
		lineageTag: b2000003-0000-0000-0000-000000000009
		summarizeBy: average
		sourceColumn: TurbolaserBatteriesOnline

		annotation SummarizationSetBy = Automatic

	column TurbolaserBatteriesTotal
		dataType: int64
		formatString: #,0
		lineageTag: b2000003-0000-0000-0000-00000000000a
		summarizeBy: average
		sourceColumn: TurbolaserBatteriesTotal

		annotation SummarizationSetBy = Automatic

	column SortiesFlown
		dataType: int64
		formatString: #,0
		lineageTag: b2000003-0000-0000-0000-00000000000b
		summarizeBy: sum
		sourceColumn: SortiesFlown

		annotation SummarizationSetBy = Automatic

	partition FactReadiness = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Csv.Document(File.Contents("b:\VS Code Files\PBI Projects\Star Wars\data\FactReadiness.csv"), [Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangeTypes = Table.TransformColumnTypes(PromoteHeaders, {
				        {"SnapshotDateKey", Int64.Type},
				        {"ConditionKey", Int64.Type},
				        {"ThreatIndex", type number},
				        {"TIESquadronsOperational", Int64.Type},
				        {"TIESquadronsTotal", Int64.Type},
				        {"SuperlaserChargePct", type number},
				        {"ShieldIntegrityPct", type number},
				        {"TurbolaserBatteriesOnline", Int64.Type},
				        {"TurbolaserBatteriesTotal", Int64.Type},
				        {"SortiesFlown", Int64.Type}
				    })
				in
				    ChangeTypes

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

