table FactLedger
	lineageTag: b1000001-0000-0000-0000-000000000001

	column LedgerID
		dataType: string
		isHidden
		lineageTag: b1000001-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: LedgerID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b1000001-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column DepartmentKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b1000001-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: DepartmentKey

		annotation SummarizationSetBy = Automatic

	column AccountKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b1000001-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: AccountKey

		annotation SummarizationSetBy = Automatic

	column VendorKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b1000001-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: VendorKey

		annotation SummarizationSetBy = Automatic

	column AmountCredits
		dataType: int64
		formatString: #,0
		lineageTag: b1000001-0000-0000-0000-000000000007
		summarizeBy: sum
		sourceColumn: AmountCredits

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		lineageTag: b1000001-0000-0000-0000-000000000008
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Status
		dataType: string
		lineageTag: b1000001-0000-0000-0000-000000000009
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition FactLedger = m
		mode: import
		queryGroup: Model
		source =
				let
				    Source = Csv.Document(File.Contents("b:\VS Code Files\PBI Projects\Star Wars\data\FactLedger.csv"), [Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangeTypes = Table.TransformColumnTypes(PromoteHeaders, {
				        {"LedgerID", type text},
				        {"DateKey", Int64.Type},
				        {"DepartmentKey", Int64.Type},
				        {"AccountKey", Int64.Type},
				        {"VendorKey", Int64.Type},
				        {"AmountCredits", Int64.Type},
				        {"Quantity", type number},
				        {"Status", type text}
				    })
				in
				    ChangeTypes

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

