table 'Measure Table'
	lineageTag: e9058282-f815-4759-b014-481340473222

	measure 'Dates Selected' = ```
			
			// Return selected Dates: Years, Month & Year, use with v3 date table
			
			    /* _________________________________________________________________________________________________________________________________________________________ */
			    // Adjust this variable to change the prefix used for the period title
			    VAR __PeriodPrefix =                "Selected Period: "
			    VAR __DiverseDates =                "a range of dates in "
			
			    // Define main start and end dates
			    VAR __StartDate =                   MIN( 'DimDate'[Date] )
			    VAR __EndDate =                     MAX( 'DimDate'[Date] )
			
			    // Provide information about the current context
			    VAR __DaysInCurrentContext =        COUNTROWS( DimDate ) 
			    VAR __DaysBetween_StartAndEnd =     DATEDIFF( __StartDate, __EndDate, DAY )  + 1
			    VAR __IsConsecutivePeriod =         __DaysBetween_StartAndEnd = __DaysInCurrentContext
			
			    // Day Related Variables
			    VAR __FormattedEndDate =            FORMAT( __EndDate, "d mmm yyyy" ) 
			
			    // Month related variables
			    VAR __FormattedStartDateMonth =     FORMAT( __StartDate, "mmm yyyy" )
			    VAR __FormattedEndMonth =           FORMAT( __EndDate,   "mmm yyyy" ) // "d mmm yyyy"
			    VAR __FiltersFullMonthsOnly =
			            VAR YearsSummary = SUMMARIZECOLUMNS( DimDate[MonthOfYear], 'DimDate'[Days In Month] )
			            VAR DaysInYears = ADDCOLUMNS( YearsSummary, "@DaysInContext", CALCULATE( COUNTROWS( DimDate ) ) )
			            VAR IncompleteMonths = FILTER( DaysInYears, [@DaysInContext] <> 'DimDate'[Days In Month] )
			            VAR Result = ISEMPTY( IncompleteMonths )
			        RETURN
			            Result
			
			    // Year related variables
			    VAR __IsSingleYear =                HASONEVALUE( 'DimDate'[Year] )
			    VAR __FiltersFullYearsOnly =
			        VAR YearsSummary = 
			            VALUES( 'DimDate'[Year] )
			        VAR IncompleteYearFlag = 
			            ADDCOLUMNS(
			                YearsSummary,
			                "@IsIncompleteYear",
			                    VAR DatesInContext = CALCULATE( COUNTROWS( DimDate ) )
			                    VAR DatesInYear = CALCULATE( MAX( 'DimDate'[Days in Year] ) )
			                    VAR IncompleteYearInContext = DatesInContext <> DatesInYear
			                RETURN
			                    IncompleteYearInContext
			                )
			        VAR IncompleteYears = 
			            FILTER(
			                IncompleteYearFlag,
			                [@IsIncompleteYear] = TRUE()
			                )
			        VAR Result = ISEMPTY( IncompleteYears )
			    RETURN
			        Result
			    VAR __Result = 
			        SWITCH( TRUE(),
			    /* _________________________________________________________________________________________________________________________________________________________  
			    Logic for creating a YEAR selection string */
			    
			    // Perform this logic only if full years are selected
			        __FiltersFullYearsOnly, 
			        
			        // Retrieve all Period Combinations that exist in the current filter context
			        VAR SelectedYears = VALUES( 'DimDate'[Year] )
			        // Find what the previous and next period is in the selection and add the values as a column
			        VAR AddPrev_Next_Year = 
			            ADDCOLUMNS(
			                SelectedYears,
			                "@PreviousPeriod", 
			                MAXX(
			                    FILTER(	SelectedYears,
			                        'DimDate'[Year] < EARLIER( 'DimDate'[Year] ) ),
			                    'DimDate'[Year] ),
			                "@NextPeriod", 
			                MINX(
			                    FILTER(	SelectedYears,
			                        'DimDate'[Year] > EARLIER( 'DimDate'[Year] ) ),
			                    'DimDate'[Year] )
			            )
			        /* Based on whether the previous or next period combination in the context is consecutive, define logic.
			            - The very last combination should end with a regular year value.
			            - The start of a range should start with a period and end with a dash "-" to indicate the start of a range
			            - All values within a range return blank, they don't need to be included
			            - A single month (outside of a range) or the last month in a range should both show: Period and a separator ( pipe symbol ) */
			            
			        VAR __ConcatenationLogic = 
			            ADDCOLUMNS( 
			                AddPrev_Next_Year,
			                "@PartOfRange",
			                    VAR __NextPeriod =  'DimDate'[Year] + 1
			                    VAR __PrevPeriod =  'DimDate'[Year] - 1
			                    VAR __StringElements = 
			                        SWITCH( TRUE(),
			                            ISBLANK( [@NextPeriod] ), 											      'DimDate'[Year], 	        // The last period in the context
			                            __NextPeriod <> [@NextPeriod] && __PrevPeriod <> [@PreviousPeriod],       'DimDate'[Year] & " | " ,    // A period outside of a range 
			                            __NextPeriod <> [@NextPeriod] && __PrevPeriod =  [@PreviousPeriod],       'DimDate'[Year] & " | " ,    // The last period value in a range
			                            __NextPeriod =  [@NextPeriod] && __PrevPeriod <> [@PreviousPeriod],       'DimDate'[Year] & " - " , 	// The first [Period] in a range
			                            __NextPeriod =  [@NextPeriod] && __PrevPeriod =  [@PreviousPeriod],       BLANK(), 					    // A period in the middle of a range
			                            __NextPeriod <> [@NextPeriod] && __PrevPeriod =  [@PreviousPeriod],       'DimDate'[Year] & " | "      // The last period in a range
			                        )
			                    RETURN __StringElements
			            )
			        RETURN
			        __PeriodPrefix & CONCATENATEX( __ConcatenationLogic, [@PartOfRange], "", 'DimDate'[Year], ASC ),
			            
			    /* _________________________________________________________________________________________________________________________________________________________
			        For month selections below calculation returns the right values: */
			            
			    // Check if users filter full months only
			        __FiltersFullMonthsOnly,
			        
			    // Retrieve all Start of Month Combinations that exist in the current filter context
			        VAR SelectedDates = VALUES( 'DimDate'[Start Of Month] )
			        VAR __MultipleYearsInContext = YEAR( __StartDate ) <> YEAR( __EndDate )
			        
			        // Find what the previous and next month-year combination is and add the values as a column
			        VAR AddPreviousDates = 
			            ADDCOLUMNS(
			                SelectedDates,
			                "@PreviousMonthYear", 
			                MAXX(
			                    FILTER(	SelectedDates,
			                        'DimDate'[Start Of Month] < EARLIER( 'DimDate'[Start Of Month] ) ),
			                    'DimDate'[Start Of Month] ),
			                "@NextMonthYear", 
			                MINX(
			                    FILTER(	SelectedDates,
			                        'DimDate'[Start Of Month] > EARLIER( 'DimDate'[Start Of Month] ) ),
			                    'DimDate'[Start Of Month] )
			            )
			        /* Based on whether the previous or next month-year combination in the context is consecutive, define logic.
			            - The very last combination should end with both the month (short) and the year value.
			            - The start of a range should start with month (short) and end with a dash "-" to indicate the start of a range
			            - All values within a range return blank, they don't need to be included
			            - A single month (outside of a range) or the last month in a range should both show: Month (short) and a separator (pipe symbol ) */
			
			        VAR __ConcatenationLogic = 
			            ADDCOLUMNS(
			                AddPreviousDates,
			                "@PartOfRange",
			                VAR  __NextMonth = EDATE( 'DimDate'[Start Of Month], 1 )
			                VAR  __PrevMonth = EDATE( 'DimDate'[Start Of Month], - 1 )
			                VAR  __StringElements = 
			                SWITCH(
			                    TRUE(),
			                    /* __________________ Multiple year logic ____________________________ */
			                    
			                    ISBLANK( [@NextMonthYear] ), FORMAT( 'DimDate'[Start Of Month], "mmm yyyy " ),   // The last period of all periods
			                    
			                    __NextMonth = [@NextMonthYear] && __PrevMonth <> [@PreviousMonthYear] && __MultipleYearsInContext, FORMAT( 'DimDate'[Start Of Month], "mmm yyyy - " ),     // The first period in a range, when multiple years are selected
			
			
			                    YEAR( [@NextMonthYear] ) <> YEAR( 'DimDate'[Start Of Month] ) && NOT ( __IsConsecutivePeriod ), FORMAT( 'DimDate'[Start Of Month], "mmm yyyy | " ),       // The last period in current year (in non consecutive selection)
			                    
			                    __MultipleYearsInContext && __NextMonth <> [@NextMonthYear] && __PrevMonth <> [@PreviousMonthYear], FORMAT( 'DimDate'[Start Of Month], "mmm yyyy | " ),    // A period outside of a range
			                    __MultipleYearsInContext && __NextMonth <> [@NextMonthYear] && __PrevMonth = [@PreviousMonthYear], FORMAT( 'DimDate'[Start Of Month], "mmm yyyy | " ),     // Last period value in a range
			                    
			                    /* __________________ Single Year Logic   ____________________________ */
			                    
			                    __NextMonth <> [@NextMonthYear] && __PrevMonth <> [@PreviousMonthYear], FORMAT( 'DimDate'[Start Of Month], "mmm | " ),     // A month outside of a range
			                    __NextMonth <> [@NextMonthYear] && __PrevMonth = [@PreviousMonthYear],  FORMAT( 'DimDate'[Start Of Month], "mmm | " ),     // The last date/month value in a range
			                    __NextMonth = [@NextMonthYear] && __PrevMonth <> [@PreviousMonthYear],  FORMAT( 'DimDate'[Start Of Month], "mmm - " ),     // The first period in a range, with a single year selection
			                    __NextMonth = [@NextMonthYear] && __PrevMonth = [@PreviousMonthYear],   BLANK()                                             // A month in the middle of a range
			                )
			                RETURN
			                __StringElements
			            )
			        VAR __RemoveMiddleOfRange = FILTER( __ConcatenationLogic, [@PartOfRange] <> "" )
			        VAR __YearRangeStartCorrection =
			            ADDCOLUMNS(
			                __RemoveMiddleOfRange,
			                "@RangeElements",
			                VAR __NextPartOfRange =
			                    MINX(
			                        FILTER(	__RemoveMiddleOfRange, 'DimDate'[Start Of Month] > EARLIER( 'DimDate'[Start Of Month] ) ),
			                        'DimDate'[Start Of Month] 
			                    )
			                VAR Result =
			                IF( 
			                    RIGHT( [@PartOfRange], 2 ) = "- " 
			                        && YEAR( __NextPartOfRange ) = YEAR( 'DimDate'[Start Of Month] ), 
			                    LEFT( [@PartOfRange], 3 ) & RIGHT( [@PartOfRange], 3 ),
			                    [@PartOfRange]
			                )
			                RETURN Result
			            )
			                        
			                        
			        RETURN
			        __PeriodPrefix & CONCATENATEX( __YearRangeStartCorrection, [@RangeElements], "", 'DimDate'[Start Of Month], ASC ),
			        
			    /* _________________________________________________________________________________________________________________________________________________________ 
			            When the selection consists of a single day, simply return the day */
			
			            __DaysInCurrentContext = 1,
			            __PeriodPrefix & FORMAT( VALUES( 'DimDate'[Date] ), "d mmm yyyy" ),
			        
			    /* _________________________________________________________________________________________________________________________________________________________
			            Define non-consecutive periods within the same month , e.g. 1 jan 2023, 5 jan 2023, 6 jan 2023 -> 
			            returns: niet openeenvolgende datums in Jan 2023 */
			                    VAR SameYearMonth =      __FormattedStartDateMonth = __FormattedEndMonth 
			                    RETURN  
			            __IsSingleYear &&  SameYearMonth && NOT( __IsConsecutivePeriod ),
			            __PeriodPrefix & __DiverseDates & __FormattedStartDateMonth,
			
			    /* _________________________________________________________________________________________________________________________________________________________
			            Define consecutive periods within the same month , e.g. 1 - 3 jan 2023
			            returns: niet openeenvolgende datums in Jan 2023 */
			                    VAR SameYearMonth =      __FormattedStartDateMonth = __FormattedEndMonth 
			
			                    RETURN  
			            __IsSingleYear &&  SameYearMonth &&  __IsConsecutivePeriod,
			                    VAR __FormattedStartDayShort = FORMAT( __StartDate, "d" )
			                    VAR __FormattedEndDayMonth = FORMAT( __EndDate, "d mmm yyyy" )
			                RETURN
			            __PeriodPrefix & __FormattedStartDayShort & " - " & __FormattedEndDayMonth,
			
			    /* _________________________________________________________________________________________________________________________________________________________
			            Define consecutive date range within the year where end date is not end of the month, but start date is start of the month. 
			            In those cases, return the short full date format of both the start and end date , e.g. 1 jan 2023 t/m 19 feb 2023-> 
			            returns: 1 jan 2023 - 19 feb 2023*/
			                VAR __DatesNotStartTillEndOfMonth =      __EndDate <>  EOMONTH( __EndDate, 0 ) || __StartDate =  ( EOMONTH( __StartDate, - 1 ) + 1 )
			            RETURN
			            __IsSingleYear && __DatesNotStartTillEndOfMonth /* && __StartDate_IsStartOfMonth */ && __IsConsecutivePeriod,
			                    VAR __FormattedStartDateShort = FORMAT( __StartDate, "d mmm" ) 
			                RETURN 
			                __PeriodPrefix & __FormattedStartDateShort & " - " & __FormattedEndDate
			            
			        )
			    RETURN     
			        
			    SWITCH(
			        TRUE(),
			        ISBLANK( __Result ), "Selected Period: See Date Slicers",
			        __Result
			    )
			
			////
			
			
			
			
			
			
			
			
			
			
			
			```
		displayFolder: Time Intelligence
		lineageTag: 0d4d8f72-bef0-435c-a99e-45ebef7e4ffb

	measure 'Total Income' = CALCULATE ( SUM ( FactLedger[AmountCredits] ), DimAccount[AccountType] = "Income" )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Actuals
		lineageTag: d1000000-0000-0000-0000-000000000001

	measure 'Total Expenses' = CALCULATE ( SUM ( FactLedger[AmountCredits] ), DimAccount[AccountType] = "Expense" )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Actuals
		lineageTag: d1000000-0000-0000-0000-000000000002

	measure 'Net Surplus' = [Total Income] - [Total Expenses]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Actuals
		lineageTag: d1000000-0000-0000-0000-000000000003

	measure 'Operating Margin %' = DIVIDE ( [Net Surplus], [Total Income] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Financials\Actuals
		lineageTag: d1000000-0000-0000-0000-000000000004

	measure 'Imperial Subsidy' = CALCULATE ( SUM ( FactLedger[AmountCredits] ), DimAccount[ImperialSubsidy] = "Yes" )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Actuals
		lineageTag: d1000000-0000-0000-0000-000000000005

	measure 'Subsidy Coverage %' = DIVIDE ( [Imperial Subsidy], [Total Expenses] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Financials\Actuals
		lineageTag: d1000000-0000-0000-0000-000000000006

	measure 'Expenses YoY %' =
			DIVIDE (
			    [Total Expenses] - CALCULATE ( [Total Expenses], DATEADD ( DimDate[Date], -1, YEAR ) ),
			    CALCULATE ( [Total Expenses], DATEADD ( DimDate[Date], -1, YEAR ) )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Financials\Year over Year
		lineageTag: d1000000-0000-0000-0000-000000000007

	measure 'Total Headcount' = SUM ( FactHeadcount[Headcount] )
		formatString: #,0
		displayFolder: Headcount\Actuals
		lineageTag: d1000000-0000-0000-0000-000000000008

	measure 'Combat Losses' = SUM ( FactHeadcount[CombatLosses] )
		formatString: #,0
		displayFolder: Headcount\Actuals
		lineageTag: d1000000-0000-0000-0000-000000000009

	measure 'Attrition %' = DIVIDE ( SUM ( FactHeadcount[Separations] ), SUM ( FactHeadcount[Headcount] ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Headcount\Actuals
		lineageTag: d1000000-0000-0000-0000-00000000000a

	measure 'Payroll Cost' = SUM ( FactHeadcount[PayrollCostCredits] )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Headcount\Payroll
		lineageTag: d1000000-0000-0000-0000-00000000000b

	measure 'Inventory Value' =
			VAR LastSnap =
			    CALCULATE ( MAX ( FactInventory[SnapshotDateKey] ), ALLSELECTED ( DimDate ) )
			RETURN
			    CALCULATE (
			        SUM ( FactInventory[InventoryValueCredits] ),
			        FactInventory[SnapshotDateKey] = LastSnap
			    )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Operations\Inventory
		lineageTag: d1000000-0000-0000-0000-00000000000c

	measure 'Stockout Lines' = CALCULATE ( COUNTROWS ( FactInventory ), FactInventory[StockStatus] = "Stockout" )
		formatString: #,0
		displayFolder: Operations\Inventory
		lineageTag: d1000000-0000-0000-0000-00000000000d

	measure 'Work Orders' = COUNTROWS ( FactMaintenance )
		formatString: #,0
		displayFolder: Operations\Maintenance
		lineageTag: d1000000-0000-0000-0000-00000000000e

	measure 'Open Work Orders' = CALCULATE ( COUNTROWS ( FactMaintenance ), FactMaintenance[Status] <> "Closed" )
		formatString: #,0
		displayFolder: Operations\Maintenance
		lineageTag: d1000000-0000-0000-0000-00000000000f

	measure 'Total Downtime Hrs' = SUM ( FactMaintenance[DowntimeHours] )
		formatString: #,0.0
		displayFolder: Operations\Maintenance
		lineageTag: d1000000-0000-0000-0000-000000000010

	measure 'Repair Cost' = SUM ( FactMaintenance[RepairCostCredits] )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Operations\Maintenance
		lineageTag: d1000000-0000-0000-0000-000000000011

	measure 'Headcount Last Year' = CALCULATE([Total Headcount], DATEADD(DimDate[Date],-1 , YEAR))
		formatString: 0
		displayFolder: Headcount\Year over Year
		lineageTag: 2a9049d6-8efa-4d49-9f38-420d84b9154e

	measure 'Headcount Variance to LY' = [Total Headcount] - [Headcount Last Year]
		formatString: 0
		displayFolder: Headcount\Year over Year
		lineageTag: f3a4f590-c0f7-48dd-b5c0-da0e3d12852c

	measure 'Headcount Var to LY %' = DIVIDE([Headcount Variance to LY], [Headcount Last Year])
		displayFolder: Headcount\Year over Year
		lineageTag: 8acf9bb5-ce64-49c0-8a20-a275554304ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Alias for Imperial Subsidy. Treat this as the canonical income for DSMS:
	/// the Death Star has no organic revenue, so all income is the Treasury subsidy.
	/// The other "income" account types (Tribute, Levies, Salvage, etc.) are kept
	/// in the ledger as historical postings but are not surfaced as headline income.
	measure 'Subsidy Income' = [Imperial Subsidy]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Actuals
		lineageTag: d1000000-0000-0000-0000-000000000020

	/// Apportions the total Imperial Treasury subsidy across departments by
	/// CostDriverWeight. Sums to total subsidy at the grand-total level;
	/// splits proportionally when filtered by department(s).
	measure 'Department Subsidy Allocation' =
			VAR TotalSubsidyAll = CALCULATE ( [Imperial Subsidy], ALL ( DimDepartment ) )
			VAR TotalWeightAll  = CALCULATE ( SUM ( DimDepartment[CostDriverWeight] ), ALL ( DimDepartment ) )
			VAR CurrentWeight   = SUM ( DimDepartment[CostDriverWeight] )
			RETURN
			    DIVIDE ( CurrentWeight * TotalSubsidyAll, TotalWeightAll )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Allocation
		lineageTag: d1000000-0000-0000-0000-000000000021

	measure 'Income Budget' = SUM ( FactBudget[IncomeBudgetCredits] )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000022

	measure 'Expense Budget' = SUM ( FactBudget[ExpenseBudgetCredits] )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000023

	/// Allocated subsidy minus income budget. Positive = over budget (good).
	measure 'Income Variance' = [Department Subsidy Allocation] - [Income Budget]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000024

	measure 'Income Variance %' = DIVIDE ( [Income Variance], [Income Budget] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Financials\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000025

	/// Actual expenses minus expense budget. Positive = over budget (bad).
	measure 'Expense Variance' = [Total Expenses] - [Expense Budget]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000026

	measure 'Expense Variance %' = DIVIDE ( [Expense Variance], [Expense Budget] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Financials\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000027

	/// Actual net (allocated income - actual expenses) minus budgeted net.
	measure 'Net Surplus vs Budget' = ( [Department Subsidy Allocation] - [Total Expenses] ) - ( [Income Budget] - [Expense Budget] )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000028

	measure 'Budgeted Headcount' = SUM ( FactBudgetHeadcount[BudgetedHeadcount] )
		formatString: #,0
		displayFolder: Headcount\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000030

	/// Actual headcount minus budgeted headcount. Positive = over plan.
	measure 'Headcount vs Budget' = [Total Headcount] - [Budgeted Headcount]
		formatString: +#,0;-#,0;0
		displayFolder: Headcount\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000031

	measure 'Headcount vs Budget %' = DIVIDE ( [Headcount vs Budget], [Budgeted Headcount] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Headcount\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000032

	/// Headcount-weighted average of the planned monthly pay rate per role.
	/// Sum of budgeted payroll cost divided by sum of budgeted headcount.
	measure 'Budgeted Avg Monthly Pay' =
			DIVIDE (
			    SUM ( FactBudgetHeadcount[BudgetedPayrollCostCredits] ),
			    SUM ( FactBudgetHeadcount[BudgetedHeadcount] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Headcount\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000033

	measure 'Budgeted Payroll Cost' = SUM ( FactBudgetHeadcount[BudgetedPayrollCostCredits] )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Headcount\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000034

	/// Actual payroll cost minus budgeted payroll cost. Positive = over budget (bad).
	measure 'Payroll Cost vs Budget' = [Payroll Cost] - [Budgeted Payroll Cost]
		formatString: \$+#,0;(\$#,0);\$0
		displayFolder: Headcount\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000035

	measure 'Payroll Cost vs Budget %' = DIVIDE ( [Payroll Cost vs Budget], [Budgeted Payroll Cost] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Headcount\Budget vs Actual
		lineageTag: d1000000-0000-0000-0000-000000000036

	measure Engagements = COUNTROWS ( FactEngagement )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-000000000001

	measure 'Active Engagements' = CALCULATE ( COUNTROWS ( FactEngagement ), FactEngagement[Status] = "Active" )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-000000000002

	measure 'Planned Engagements' = CALCULATE ( COUNTROWS ( FactEngagement ), FactEngagement[Status] = "Planned" )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-000000000003

	measure 'Engagements Won' = CALCULATE ( COUNTROWS ( FactEngagement ), FactEngagement[Status] = "Won" )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-000000000004

	measure 'Engagements Lost' = CALCULATE ( COUNTROWS ( FactEngagement ), FactEngagement[Status] = "Lost" )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-000000000005

	/// Win rate over decided engagements only (Won / (Won + Lost)).
	measure 'Win Rate %' = DIVIDE ( [Engagements Won], [Engagements Won] + [Engagements Lost] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-000000000006

	measure 'Friendly Losses' = SUM ( FactEngagement[FriendlyLosses] )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-000000000007

	measure 'Enemy Losses' = SUM ( FactEngagement[EnemyLosses] )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-000000000008

	/// Enemy losses inflicted per friendly loss sustained. Higher is better.
	measure 'Combat Exchange Ratio' = DIVIDE ( [Enemy Losses], [Friendly Losses] )
		formatString: #,0.0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-000000000009

	measure 'Friendly Craft Lost' = SUM ( FactEngagement[FriendlyCraftLost] )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-00000000000a

	measure 'Enemy Craft Destroyed' = SUM ( FactEngagement[EnemyCraftLost] )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-00000000000b

	measure 'Ordnance Expended' = SUM ( FactEngagement[OrdnanceExpended] )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-00000000000c

	measure 'Superlaser Strikes' = CALCULATE ( COUNTROWS ( FactEngagement ), FactEngagement[SuperlaserStrike] = "Yes" )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-00000000000d

	measure 'Planets Destroyed' = CALCULATE ( COUNTROWS ( FactEngagement ), FactEngagement[PlanetDestroyed] = "Yes" )
		formatString: #,0
		displayFolder: Operations Command\Engagements
		lineageTag: d2000000-0000-0000-0000-00000000000e

	measure 'Station Attacks' = COUNTROWS ( FactStationAttack )
		formatString: #,0
		displayFolder: Operations Command\Station Defense
		lineageTag: d2000000-0000-0000-0000-00000000000f

	measure 'Attacks Repelled' = CALCULATE ( COUNTROWS ( FactStationAttack ), FactStationAttack[Repelled] = "Yes" )
		formatString: #,0
		displayFolder: Operations Command\Station Defense
		lineageTag: d2000000-0000-0000-0000-000000000010

	measure 'Attacks Repelled %' = DIVIDE ( [Attacks Repelled], [Station Attacks] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Operations Command\Station Defense
		lineageTag: d2000000-0000-0000-0000-000000000011

	measure 'Hull Breaches' = CALCULATE ( COUNTROWS ( FactStationAttack ), FactStationAttack[HullBreach] = "Yes" )
		formatString: #,0
		displayFolder: Operations Command\Station Defense
		lineageTag: d2000000-0000-0000-0000-000000000012

	measure 'Attack Casualties' = SUM ( FactStationAttack[Casualties] )
		formatString: #,0
		displayFolder: Operations Command\Station Defense
		lineageTag: d2000000-0000-0000-0000-000000000013

	/// Days between the most recent attack and the end of the current period.
	measure 'Days Since Last Attack' =
			VAR MaxDate = MAX ( DimDate[Date] )
			VAR LastAttackDate = CALCULATE ( MAX ( DimDate[Date] ), FactStationAttack )
			RETURN DATEDIFF ( LastAttackDate, MaxDate, DAY )
		formatString: #,0
		displayFolder: Operations Command\Station Defense
		lineageTag: d2000000-0000-0000-0000-000000000014

	/// Readiness condition as at the latest snapshot in the current context.
	measure 'Current Readiness Condition' =
			VAR LastSnap = CALCULATE ( MAX ( FactReadiness[SnapshotDateKey] ), ALLSELECTED ( DimDate ) )
			VAR Cond = CALCULATE ( MAX ( FactReadiness[ConditionKey] ), FactReadiness[SnapshotDateKey] = LastSnap )
			RETURN LOOKUPVALUE ( DimReadinessCondition[Condition], DimReadinessCondition[ConditionKey], Cond )
		displayFolder: Operations Command\Readiness
		lineageTag: d2000000-0000-0000-0000-000000000015

	measure 'Current Threat Index' =
			VAR LastSnap = CALCULATE ( MAX ( FactReadiness[SnapshotDateKey] ), ALLSELECTED ( DimDate ) )
			RETURN CALCULATE ( MAX ( FactReadiness[ThreatIndex] ), FactReadiness[SnapshotDateKey] = LastSnap )
		formatString: 0.0
		displayFolder: Operations Command\Readiness
		lineageTag: d2000000-0000-0000-0000-000000000016

	measure 'Superlaser Charge %' =
			VAR LastSnap = CALCULATE ( MAX ( FactReadiness[SnapshotDateKey] ), ALLSELECTED ( DimDate ) )
			VAR Charge = CALCULATE ( MAX ( FactReadiness[SuperlaserChargePct] ), FactReadiness[SnapshotDateKey] = LastSnap )
			RETURN DIVIDE ( Charge, 100 )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Operations Command\Readiness
		lineageTag: d2000000-0000-0000-0000-000000000017

	measure 'Shield Integrity %' =
			VAR LastSnap = CALCULATE ( MAX ( FactReadiness[SnapshotDateKey] ), ALLSELECTED ( DimDate ) )
			VAR Shield = CALCULATE ( MAX ( FactReadiness[ShieldIntegrityPct] ), FactReadiness[SnapshotDateKey] = LastSnap )
			RETURN DIVIDE ( Shield, 100 )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Operations Command\Readiness
		lineageTag: d2000000-0000-0000-0000-000000000018

	/// Operational TIE squadrons as a share of total, at the latest snapshot.
	measure 'TIE Squadron Readiness %' =
			VAR LastSnap = CALCULATE ( MAX ( FactReadiness[SnapshotDateKey] ), ALLSELECTED ( DimDate ) )
			VAR Op = CALCULATE ( MAX ( FactReadiness[TIESquadronsOperational] ), FactReadiness[SnapshotDateKey] = LastSnap )
			VAR Tot = CALCULATE ( MAX ( FactReadiness[TIESquadronsTotal] ), FactReadiness[SnapshotDateKey] = LastSnap )
			RETURN DIVIDE ( Op, Tot )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Operations Command\Readiness
		lineageTag: d2000000-0000-0000-0000-000000000019

	measure 'Sorties Flown' = SUM ( FactReadiness[SortiesFlown] )
		formatString: #,0
		displayFolder: Operations Command\Readiness
		lineageTag: d2000000-0000-0000-0000-00000000001a

	measure 'Avg Threat Index' = AVERAGE ( FactReadiness[ThreatIndex] )
		formatString: 0.0
		displayFolder: Operations Command\Readiness
		lineageTag: d2000000-0000-0000-0000-00000000001b

	/// NARRATIVE & RISK pack (lineage d3000000-*) — surfaces the rise-and-fall arc
	/// climaxing at the Battle of Yavin (last day in the model, 31 Dec 2024).
	/// Countdown (in days) from the as-of date to the Battle of Yavin.
	/// Use as a narrative KPI or a reference line on time charts.
	measure 'Days to Battle of Yavin' =
			VAR YavinDate = DATE ( 2024, 12, 31 )
			VAR AsOf = MAX ( 'DimDate'[Date] )
			RETURN DATEDIFF ( AsOf, YavinDate, DAY )
		formatString: #,0
		displayFolder: Narrative & Risk
		lineageTag: d3000000-0000-0000-0000-000000000001

	/// Spend on the Engineering & Power division (reactor core, hypermatter
	/// fuel, power, structural). This is the system that holds the fatal flaw.
	measure 'Reactor Complex Spend' = CALCULATE ( [Total Expenses], DimDepartment[DivisionGroup] = "Engineering & Power" )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Narrative & Risk
		lineageTag: d3000000-0000-0000-0000-000000000002

	/// Reactor-complex spend as a share of ALL department spend.
	/// ~50% over the six years — half the budget on the thing that explodes.
	measure 'Reactor Complex Spend %' = DIVIDE ( [Reactor Complex Spend], CALCULATE ( [Total Expenses], ALL ( DimDepartment ) ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Narrative & Risk
		lineageTag: d3000000-0000-0000-0000-000000000003

	/// Maintenance downtime concentrated on the critical Engineering & Power systems.
	measure 'Reactor Complex Downtime Hrs' = CALCULATE ( [Total Downtime Hrs], DimDepartment[DivisionGroup] = "Engineering & Power" )
		formatString: #,0.0
		displayFolder: Narrative & Risk
		lineageTag: d3000000-0000-0000-0000-000000000004

	/// Average monthly headcount (heads, not head-months). Use as the denominator
	/// for per-capita measures so a year doesn't sum 12 monthly snapshots.
	measure 'Avg Monthly Headcount' = AVERAGEX ( VALUES ( 'DimDate'[Start Of Month] ), [Total Headcount] )
		formatString: #,0
		displayFolder: Narrative & Risk
		lineageTag: d3000000-0000-0000-0000-000000000005

	/// Total expenses per active trooper. Roughly doubled 5 BBY -> 0 BBY
	/// (~$0.8Bn -> ~$1.6Bn) as the station became capital-, not labour-, intensive.
	measure 'Cost per Trooper' = DIVIDE ( [Total Expenses], [Avg Monthly Headcount] )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Narrative & Risk
		lineageTag: d3000000-0000-0000-0000-000000000006

	/// "Enemy losses" inflicted by superlaser strikes — i.e. the civilian toll
	/// (Alderaan ~2.0bn). Isolates the propaganda figure from tactical combat,
	/// so the standard [Combat Exchange Ratio] can be read honestly.
	measure 'Superlaser Civilian Toll' = CALCULATE ( [Enemy Losses], FactEngagement[SuperlaserStrike] = "Yes" )
		formatString: #,0
		displayFolder: Narrative & Risk
		lineageTag: d3000000-0000-0000-0000-000000000007

	/// Repel rate on CRITICAL-severity attacks only. The cracks hide here:
	/// every non-repelled attack in the record was Critical severity.
	measure 'Critical Attacks Repelled %' =
			DIVIDE (
			    CALCULATE ( [Attacks Repelled], FactStationAttack[Severity] = "Critical" ),
			    CALCULATE ( [Station Attacks], FactStationAttack[Severity] = "Critical" )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Narrative & Risk
		lineageTag: d3000000-0000-0000-0000-000000000008

	/// Attacks that were NOT repelled. 126/127 were stopped; the one that
	/// wasn't is the only one that mattered (Battle of Yavin).
	measure 'Attacks Breached' = [Station Attacks] - [Attacks Repelled]
		formatString: #,0
		displayFolder: Narrative & Risk
		lineageTag: d3000000-0000-0000-0000-000000000009

	/// Year-over-year change in the average threat index. Positive = escalating.
	measure 'Threat Index YoY Change' =
			VAR Curr = [Avg Threat Index]
			VAR Prior = CALCULATE ( [Avg Threat Index], DATEADD ( 'DimDate'[Date], -1, YEAR ) )
			RETURN Curr - Prior
		formatString: +0.0;-0.0;0.0
		displayFolder: Narrative & Risk
		lineageTag: d3000000-0000-0000-0000-00000000000a

	/// Exchange ratio EXCLUDING superlaser strikes — the honest tactical figure.
	/// Pair with [Combat Exchange Ratio] (which Alderaan inflates to ~1,126:1) via the
	/// 'Exchange Ratio View' field parameter. NOTE: still outlier-sensitive in 0 BBY,
	/// where the station's own destruction (1.7M friendly losses) drags it down — that
	/// collapse is itself the story; filter to earlier years to see the steady ~2.5:1.
	measure 'Combat Exchange Ratio (Tactical)' =
			DIVIDE (
			    CALCULATE ( [Enemy Losses], FactEngagement[SuperlaserStrike] = "No" ),
			    CALCULATE ( [Friendly Losses], FactEngagement[SuperlaserStrike] = "No" )
			)
		formatString: #,0.0
		displayFolder: Narrative & Risk
		lineageTag: d3000000-0000-0000-0000-00000000000b

	/// Pareto cumulative share of expenses, descending by department spend.
	/// Put on a line over a value-sorted [Total Expenses] bar to make an 80/20 chart.
	measure 'Cumulative Expense %' =
			VAR CurrentExpense = [Total Expenses]
			VAR DeptExpense =
			    CALCULATETABLE (
			        ADDCOLUMNS ( VALUES ( DimDepartment[Department] ), "@e", [Total Expenses] ),
			        ALLSELECTED ( DimDepartment )
			    )
			VAR RunningTotal = SUMX ( FILTER ( DeptExpense, [@e] >= CurrentExpense ), [@e] )
			VAR GrandTotal = SUMX ( DeptExpense, [@e] )
			RETURN DIVIDE ( RunningTotal, GrandTotal )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Financials\Actuals
		lineageTag: d3000000-0000-0000-0000-00000000000c

	/// Hex colour for the current readiness condition (Green/Blue/Yellow/Red/Black)
	/// at the latest snapshot. Use as a "by field value" conditional-format colour on
	/// the threat card / line so the posture band is visible at a glance.
	measure 'Threat Alert Color' =
			VAR LastSnap = CALCULATE ( MAX ( FactReadiness[SnapshotDateKey] ), ALLSELECTED ( DimDate ) )
			VAR Cond = CALCULATE ( MAX ( FactReadiness[ConditionKey] ), FactReadiness[SnapshotDateKey] = LastSnap )
			VAR Color = LOOKUPVALUE ( DimReadinessCondition[AlertColor], DimReadinessCondition[ConditionKey], Cond )
			RETURN
			    SWITCH (
			        Color,
			        "Green", "#1E7C36",
			        "Blue", "#1F4E8C",
			        "Yellow", "#E0A400",
			        "Red", "#C62F2F",
			        "Black", "#1A1A1A",
			        "#999999"
			    )
		displayFolder: Operations Command\Readiness
		lineageTag: d3000000-0000-0000-0000-00000000000d

	/// Monthly net cash: subsidy in minus expenses out. Negative = the station
	/// spent more than the Empire funded that period.
	measure 'Net Cash Flow' = [Total Income] - [Total Expenses]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Cash
		lineageTag: d3000000-0000-0000-0000-00000000000e

	/// Running cash position. Goes NEGATIVE after an attack because repair spend
	/// hits now but the Empire's funding increase only arrives ~2 months later
	/// (the funding-application delay) — the station borrows to bridge the gap.
	measure 'Cumulative Cash Position' =
			VAR MaxDate = MAX ( 'DimDate'[Date] )
			RETURN
			    CALCULATE (
			        [Net Cash Flow],
			        FILTER ( ALLSELECTED ( 'DimDate' ), 'DimDate'[Date] <= MaxDate )
			    )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financials\Cash
		lineageTag: d3000000-0000-0000-0000-00000000000f

	/// Days the cash position has been underwater in the selected period — the
	/// metric Command wants to drive down by shortening the funding-application lag.
	measure 'Months Cash Negative' =
			SUMX (
			    VALUES ( 'DimDate'[Start Of Month] ),
			    VAR EoM = CALCULATE ( MAX ( 'DimDate'[Date] ) )
			    VAR Cash =
			        CALCULATE (
			            [Net Cash Flow],
			            FILTER ( ALLSELECTED ( 'DimDate' ), 'DimDate'[Date] <= EoM )
			        )
			    RETURN IF ( Cash < 0, 1, 0 )
			)
		formatString: #,0
		displayFolder: Financials\Cash
		lineageTag: d3000000-0000-0000-0000-000000000010

	column Column1
		dataType: string
		isHidden
		lineageTag: 43150b8b-19be-4bf5-8f81-3ce374a32384
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Measure Table' = m
		mode: import
		queryGroup: Others
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t])
				in
				    Source

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

