/**
 * wire-spec.mjs
 * Takes an approved .vl.json5 mockup spec and scaffolds production files:
 *   src/queries/<domain>/<name>.json   — clean Vega-Lite spec (no sample data)
 *   src/queries/<domain>/<name>.ts     — factory file with TODO column mappings
 *   src/queries/<domain>/<name>.dax    — empty DAX query skeleton
 *
 * Usage:
 *   npm run wire-spec -- mockups/bullet-chart.vl.json5 --domain bullet --name bullet-chart
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join, resolve, basename, extname } from "node:path";
import { parseArgs } from "node:util";
import JSON5 from "json5";

// --- Argument parsing ---
const { values: args, positionals } = parseArgs({
    options: {
        domain: { type: "string" },
        name:   { type: "string" },
    },
    allowPositionals: true,
});

const srcArg = positionals[0];
if (!srcArg || !args.domain || !args.name) {
    console.error("Usage: npm run wire-spec -- <mockup.vl.json5> --domain <domain> --name <name>");
    console.error("Example: npm run wire-spec -- mockups/bullet-chart.vl.json5 --domain bullet --name bullet-chart");
    process.exit(1);
}

const srcPath = resolve(srcArg);
const domain = args.domain;
const name = args.name;
const outDir = resolve(process.cwd(), "src", "queries", domain);

await mkdir(outDir, { recursive: true });

// --- Parse the JSON5 source spec ---
const raw = await readFile(srcPath, "utf8");
let spec;
try {
    spec = JSON5.parse(raw);
} catch (err) {
    console.error(`❌ Failed to parse ${basename(srcPath)}: ${err.message}`);
    process.exit(1);
}

// --- Extract DATA BINDING comments for field hints ---
const bindingLines = [];
for (const line of raw.split("\n")) {
    const m = line.match(/\/\/\s+(\w+)\s*:\s*(string|number|date)\s*[—-]+\s*(dimension|measure)\s*[—-]+\s*(.*)/);
    if (m) bindingLines.push({ name: m[1], type: m[2], role: m[3], dax_hint: m[4].trim() });
}

// --- Extract all field references from spec encoding ---
const fieldNames = new Set();
function extractFields(obj) {
    if (!obj || typeof obj !== "object") return;
    if (Array.isArray(obj)) { obj.forEach(extractFields); return; }
    if (obj.field && typeof obj.field === "string") fieldNames.add(obj.field);
    for (const v of Object.values(obj)) extractFields(v);
}
extractFields(spec);

// Merge: prefer binding hints, fall back to field names found in spec
const allFields = [...fieldNames].map(fname => {
    const hint = bindingLines.find(b => b.name === fname);
    return hint ?? { name: fname, type: "?", role: "?", dax_hint: "TODO" };
});

// --- Write .json spec (strip sample data, ensure table source) ---
const prodSpec = { ...spec };
if (prodSpec.data?.values) {
    prodSpec.data = { name: "table" };
}
// Remove facet's sample data too (bullet charts)
const specJson = JSON.stringify(prodSpec, null, 2);
await writeFile(join(outDir, `${name}.json`), specJson);
console.log(`✅ Spec    → src/queries/${domain}/${name}.json`);

// --- Write .dax skeleton ---
const fieldComments = allFields
    .map(f => `-- ${f.name.padEnd(20)} : ${f.type.padEnd(6)} (${f.role})   ${f.dax_hint}`)
    .join("\n");

const daxContent = `-- ${name}.dax
-- Auto-generated by wire-spec — fill in the real DAX query below
--
-- Expected output columns (from DATA BINDING in source spec):
${fieldComments}
--
-- Example structure:
-- EVALUATE
-- SUMMARIZECOLUMNS(
--     <dimension columns>,
--     "field_name", [Measure]
-- )
-- ORDER BY <sort column> ASC

`;
await writeFile(join(outDir, `${name}.dax`), daxContent);
console.log(`✅ DAX     → src/queries/${domain}/${name}.dax`);

// --- Write .ts factory ---
const connectionAlias = domain; // defaults to domain name; user can change

const metadataEntries = allFields
    .map(f => {
        const key = f.dax_hint !== "TODO" ? `"${f.dax_hint}"` : `"TODO: ${f.name}"`;
        return `    // TODO: replace key with exact column name from CLI query output
    ${key}: { name: "${f.name}", displayName: "${toDisplayName(f.name)}"${f.type === "number" ? ', format: "#,##0"' : ""} },`;
    })
    .join("\n");

const camelName = toCamelCase(name);
const tsContent = `import type { VisualizationSpec } from "@microsoft/fabric-visuals";
import type { ColumnMetadataMap } from "@/lib/to-data-table";
import spec from "./${name}.json";
import query from "./${name}.dax?raw";

const connection = "${connectionAlias}";

/**
 * Column metadata — keys must be the EXACT column names from CLI query output.
 * Run: npx fabric-app-data query ${connectionAlias} --file src/queries/${domain}/${name}.dax --limit 1
 * Then copy the column names from the output as the dictionary keys.
 */
const columnMetadata: ColumnMetadataMap = {
${metadataEntries}
};

export function ${camelName}() {
    return {
        connection,
        query,
        columnMetadata,
        vegaLiteSpec: spec as VisualizationSpec,
    };
}
`;
await writeFile(join(outDir, `${name}.ts`), tsContent);
console.log(`✅ Factory → src/queries/${domain}/${name}.ts`);

console.log(`
────────────────────────────────────────────────────────
Next steps:
  1. Write the DAX query in src/queries/${domain}/${name}.dax
  2. Test it: npx fabric-app-data query ${connectionAlias} --file src/queries/${domain}/${name}.dax --limit 5
  3. Copy exact column names from CLI output → update columnMetadata keys in ${name}.ts
  4. Import ${camelName}() in your React component:
       const { connection, query, columnMetadata, vegaLiteSpec } = ${camelName}();
       const { data } = useSemanticModelQuery({ connection, query });
       const table = toDataTable(data.table, columnMetadata);
       return <VegaVisual spec={vegaLiteSpec} data={table} theme={theme} />;
────────────────────────────────────────────────────────`);

// --- Helpers ---
function toDisplayName(snake) {
    return snake.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
}
function toCamelCase(kebab) {
    return kebab.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}
